### ISSUE TITLE
Include images in readme

### ISSUE THREAD

**Issue by JakeHartnell** [CommonGarden/Fermenter#2]

**Comment by catbarph** [comment]
![img_3484 1](https://user-images.githubusercontent.com/3916616/31311867-302da26a-ab6a-11e7-94c6-34defbc47ef5.jpg)
![img_4011](https://user-images.githubusercontent.com/3916616/31311866-302be5d8-ab6a-11e7-9963-6187714b8f64.jpg)
![img_4020](https://user-images.githubusercontent.com/3916616/31311864-302a24d2-ab6a-11e7-9593-81c027f5dcda.jpg)
![img_4025](https://user-images.githubusercontent.com/3916616/31311865-302a8634-ab6a-11e7-86b6-895c111c9780.jpg)

**Comment by JakeHartnell** [comment]
![doser](https://user-images.githubusercontent.com/521978/31350657-d8236afe-acdc-11e7-8cbd-e6826b2f679a.jpg)
